name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: configure
    #   run: ./configure
    - name: cd
      run: mkdir build && cd build
    - name: cmake
      run: cmake -B build -S .
    - name: make build
      run: cd build && make
